### ISSUE TITLE
Delegate callback for didChangeText occurs when programmatically setting text

### ISSUE THREAD

**Issue by shredsonic** [twostraws/Sourceful#20]
The delegate callback for `didChangeText` occurs when programmatically setting text. This doesn't match the pattern for other UIKit delegates, where they are not called when properties are programmatically set. This causes some problems when trying to implement SwiftUI features, such as the binding's setter being called when a view is first created.

**Comment by tgb20** [comment]
Would this be the reason I am running into an issue where the text is not updating when using SwiftUI?

```swift
import SwiftUI
import Sourceful

struct SampleCodeEditor: View {
    
    @State private var code = "This appears"
    
    var body: some View {
        SourceCodeTextEditor(text: $code)
            .onAppear(perform: {
                code = "This does not"
            })
    }
}
```

**Comment by shredsonic** [comment]
@tgb20 Your issue is actually caused by #21. I'll put up another PR soon to fix that problem, too.
